AWSTemplateFormatVersion: '2010-09-09'
Description: 'A user who has the privilidges to administrate the environment'
Resources:
  EnvironmentAdminUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Join ['', [!Ref "AWS::StackName", "-admin" ]]
  EnvironmentAdminUserKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'EnvironmentAdminUser'
Outputs:
  AccessKey:
    Value: !Ref 'EnvironmentAdminUserKey'
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt [EnvironmentAdminUserKey, SecretAccessKey]
    Description: AWSSecretAccessKey of new user