AWSTemplateFormatVersion: '2010-09-09'
Description: 'Environment admin user and the storage.'
Parameters:
  StackRootName:
    Type: String

Resources:
  EnvironmentAdminUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Join ['', [!Ref "StackRootName", "-admin" ]]
  EnvironmentAdminUserKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'EnvironmentAdminUser'
  StackAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Join ['', [!Ref "AWS::StackName", "-admin-policy" ]]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "cloudformation:Describe*"
              - "cloudformation:List*"
              - "cloudformation:Get*"
              - "cloudformation:Create*"
              - "cloudformation:Execute*"
            Resource: !Join ['', ["arn:aws:cloudformation:eu-central-1:332197038802:stack/", !Ref "StackRootName", "*" ]]
          - Effect: "Allow"
            Action:
              - "ecr:CreateRepository"
              - "ecr:GetAuthorizationToken"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "ecr:DescribeRepositories"
              - "ecr:SetRepositoryPolicy"
              - "ecr:PutLifecyclePolicy"
              - "ecr:DeleteRepository"
            Resource: !Join ['', ["arn:aws:ecr:eu-central-1:332197038802:repository/", !Ref "StackRootName", "*" ]]
      Users:
        - Ref: "EnvironmentAdminUser"

  EnvironmentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['', [!Ref "AWS::StackName", "-bucket" ]]
      LifecycleConfiguration:
        Rules:
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
            Status: Enabled
          - NoncurrentVersionExpirationInDays: 1
            Status: Enabled
  EnvironmentBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref EnvironmentBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Principal:
              AWS:
                - !GetAtt 'EnvironmentAdminUser.Arn'
            Action:
              - 's3:PutObject*'
              - 's3:GetObject'
            Effect: Allow
            Resource: !Sub '${EnvironmentBucket.Arn}/*'

Outputs:
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  EnvironmentAdminUserArn:
    Value: !GetAtt EnvironmentAdminUser.Arn
    Export:
      Name: !Sub '${StackRootName}-EnvironmentAdminUserArn'
  AccessKey:
    Value: !Ref 'EnvironmentAdminUserKey'
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt [EnvironmentAdminUserKey, SecretAccessKey]
    Description: AWSSecretAccessKey of new user
  BucketName:
    Description: 'Name of the bucket'
    Value: !Ref EnvironmentBucket
    Export:
      Name: !Sub '${StackRootName}-BucketName'
  BucketDomainName:
    Description: 'Domain name of the bucket.'
    Value: !GetAtt 'EnvironmentBucket.DomainName'
    Export:
      Name: !Sub '${StackRootName}-BucketDomainName'
  BucketURL:
    Description: 'URL of the bucket.'
    Value: !GetAtt 'EnvironmentBucket.WebsiteURL'
    Export:
      Name: !Sub '${StackRootName}-BucketURL'