AWSTemplateFormatVersion: '2010-09-09'
Description: 'Environment admin user and the storage.'
Parameters:
  StackRootName:
    Type: String

Resources:
  EnvironmentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['', [!Ref "StackRootName", "-storage" ]]
      LifecycleConfiguration:
        Rules:
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
            Status: Enabled
          - NoncurrentVersionExpirationInDays: 1
            Status: Enabled
  EnvironmentBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref EnvironmentBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - Fn::ImportValue: !Sub ${StackRootName}-EnvironmentAdminUserArn
            Action:
              - 's3:ListBucket'
              - 's3:DeleteBucketPolicy'
              - 's3:GetBucketPolicy'
            Resource: !Sub '${EnvironmentBucket.Arn}'
          - Effect: Allow
            Principal:
              AWS:
                - Fn::ImportValue: !Sub ${StackRootName}-EnvironmentAdminUserArn
            Action:
              - 's3:PutObject*'
              - 's3:GetObject'
              - 's3:DeleteObject'
            Resource: !Sub '${EnvironmentBucket.Arn}/*'
Outputs:
  BucketName:
    Description: 'Name of the bucket'
    Value: !Ref EnvironmentBucket
    Export:
      Name: !Sub '${StackRootName}-BucketName'
  BucketDomainName:
    Description: 'Domain name of the bucket.'
    Value: !GetAtt 'EnvironmentBucket.RegionalDomainName'
    Export:
      Name: !Sub '${StackRootName}-BucketDomainName'