AWSTemplateFormatVersion: '2010-09-09'
Description: 'A user who has the privilidges to administrate the environment'
Resources:
  EnvironmentAdminPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Join ['', [!Ref "AWS::StackName", "-admin-policy" ]]
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - 'ecr:GetAuthorizationToken'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:BatchGetImage'
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:PutImage'
              - 'ecr:InitiateLayerUpload'
              - 'ecr:UploadLayerPart'
              - 'ecr:CompleteLayerUpload'
            Resource:
              - '*'