AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  StackRootName:
    Type: String

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Join:
          - ''
          - - 'https://'
            - Fn::ImportValue:
                !Sub '${StackRootName}-BucketDomainName'
            - '/'
            - '5-network.yml'
  ClusterStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL:
        Fn::Join:
          - ''
          - - 'https://'
            - Fn::ImportValue:
                !Sub '${StackRootName}-BucketDomainName'
            - '/'
            - '6-cluster.yml'
      Parameters:
        ECSAMI: "/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id"
        VpcResource: !GetAtt 'Outputs.NetworkVpc'

  ServicesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ClusterStack
    Properties:
      TemplateURL:
        Fn::Join:
          - ''
          - - 'https://'
            - Fn::ImportValue:
                !Sub '${StackRootName}-BucketDomainName'
            - '/'
            - '7-services.yml'