AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  StackRootName:
    Type: String

Resources:
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Join:
          - ''
          - - 'https://'
            - Fn::ImportValue:
                !Sub '${StackRootName}-BucketDomainName'
            - '/'
            - '5-network.yml'
  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Join:
          - ''
          - - 'https://'
            - Fn::ImportValue:
                !Sub '${StackRootName}-BucketDomainName'
            - '/'
            - '6-cluster.yml'
      Parameters:
        ECSAMI: "/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id"
        NetworkVpc: !GetAtt 'Network.Outputs.Vpc'
        NetworkPubSubnet: !GetAtt 'Network.Outputs.PubSubnet'

  Services:
    Type: AWS::CloudFormation::Stack
    DependsOn: Cluster
    Properties:
      TemplateURL:
        Fn::Join:
          - ''
          - - 'https://'
            - Fn::ImportValue:
                !Sub '${StackRootName}-BucketDomainName'
            - '/'
            - '7-services.yml'